services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuscareai_app
    ports:
      - "8181:8181"
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:16
    container_name: postgres_cuscareai
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - .env
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8282:8282
    networks:
      - app_network  
volumes:
  postgres_data:

networks:
  app_network:
